"""
Builds the Python package's data from data/v1: the units, the census figures for both
censuses, the 2024 establishments and the crosswalk, gzipped so an install stays small.

The two fields that come from OpenStreetMap, area and density, are left out of the
communes table, as they are from the npm package. They're under ODbL, whose share-alike
terms would then cover the package; everything here is census data, attributed.

    python3 packages/morocco-communes-py/build_data.py
"""

import gzip
import json
import re
import shutil
from pathlib import Path

HERE = Path(__file__).parent
DATA = Path("data/v1")
OUT = HERE / "src" / "morocco_communes" / "data"

# source path under data/v1 -> path inside the package
TABLES = {
    "attributes/regions.csv": "attributes/regions.csv.gz",
    "attributes/provinces.csv": "attributes/provinces.csv.gz",
    "attributes/cercles.csv": "attributes/cercles.csv.gz",
    "attributes/communes.csv": "attributes/communes.csv.gz",
    "attributes/arrondissements.csv": "attributes/arrondissements.csv.gz",
    "indicators/people.csv": "indicators/people.csv.gz",
    "indicators/households.csv": "indicators/households.csv.gz",
    "indicators/2014/people.csv": "indicators2014/people.csv.gz",
    "indicators/2014/households.csv": "indicators2014/households.csv.gz",
    "economy/establishments.csv": "economy/establishments.csv.gz",
    "crosswalk/2014-2024.csv": "crosswalk/2014-2024.csv.gz",
}
DOCUMENTS = {
    "indicators/fields.json": "fields/indicators.json",
    "indicators/2014/fields.json": "fields/indicators2014.json",
    "economy/fields.json": "fields/economy.json",
    "sources.json": "sources.json",
}
# Derived from OpenStreetMap, so out, along with the boundaries themselves.
DROP = {"attributes/communes.csv": ["area_km2", "density_2024"]}


def rows(path: Path):
    """The file's lines, without the byte-order mark Excel wants."""
    text = path.read_text(encoding="utf-8-sig")
    return text.splitlines(keepends=True)


def drop_columns(lines: list[str], columns: list[str]) -> list[str]:
    """Takes named columns out of a CSV whose values never contain a comma or a quote."""
    header = lines[0].rstrip("\r\n").split(",")
    for name in columns:
        if name not in header:
            raise SystemExit(f"{name} is not a column of this file; its columns are {', '.join(header)}")
    keep = [i for i, name in enumerate(header) if name not in columns]
    out = []
    for line in lines:
        if '"' in line:
            raise SystemExit("a quoted field: this needs a real CSV reader rather than a split")
        fields = line.rstrip("\r\n").split(",")
        out.append(",".join(fields[i] for i in keep) + "\n")
    return out


def main() -> None:
    if not DATA.is_dir():
        raise SystemExit(f"run this from the repository root; {DATA} is not there")
    if OUT.exists():
        shutil.rmtree(OUT)

    for source, target in TABLES.items():
        lines = rows(DATA / source)
        if source in DROP:
            lines = drop_columns(lines, DROP[source])
        path = OUT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        # mtime 0, so the same data builds the same bytes.
        with gzip.GzipFile(path, "wb", mtime=0) as f:
            f.write("".join(lines).encode("utf-8"))

    for source, target in DOCUMENTS.items():
        path = OUT / target
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(json.loads((DATA / source).read_text(encoding="utf-8")), ensure_ascii=False), encoding="utf-8")

    version = json.loads((DATA / "sources.json").read_text(encoding="utf-8"))["datasetVersion"]
    declared = re.search(r'^version = "(.+)"$', (HERE / "pyproject.toml").read_text(encoding="utf-8"), re.M)
    if not declared:
        raise SystemExit("pyproject.toml has no version line")
    if declared.group(1) != version:
        raise SystemExit(f"pyproject.toml says {declared.group(1)}, the dataset is {version}; bump it deliberately")
    (OUT.parent / "_version.py").write_text(f'"""Generated by build.py. Do not edit."""\n\n__version__ = "{version}"\n', encoding="utf-8")

    total = sum(p.stat().st_size for p in OUT.rglob("*") if p.is_file())
    print(f"python package: {len(TABLES)} tables and {len(DOCUMENTS)} documents, {total / 1024:.0f} KB, version {version}")


if __name__ == "__main__":
    main()
