/**
 * Chart data, computed from the published dataset so every figure on the page is one the
 * API would return. Nothing here is rounded for effect or carried over from a previous
 * build — the script reads data/v1 and writes the numbers it finds.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";

const ATTR = "data/v1/attributes";

interface Commune {
  parents: { region: string };
  type: "urban" | "rural";
  population: {
    "2024": { total: number | null };
    "2014": { total: number | null } | null;
    change: { pct: number; basis: string } | null;
  };
}
interface Region {
  code: string;
  name: { fr: string };
}

const read = async <T>(name: string) => JSON.parse(await readFile(`${ATTR}/${name}.json`, "utf8")) as T;
const communes = await read<Commune[]>("communes");
const regions = await read<Region[]>("regions");

/* 1. Where the population moved between the two censuses. -------------------- */

const change = regions
  .map((region) => {
    let before = 0;
    let after = 0;
    for (const c of communes) {
      if (c.parents.region !== region.code) continue;
      if (c.population["2024"].total !== null) after += c.population["2024"].total;
      if (c.population["2014"]?.total != null) before += c.population["2014"].total;
    }
    return {
      code: region.code,
      name: region.name.fr,
      before,
      after,
      pct: Number((((after - before) / before) * 100).toFixed(1)),
    };
  })
  .sort((a, b) => b.pct - a.pct);

/* 2. How big a commune actually is. ------------------------------------------ */

const EDGES = [0, 2000, 5000, 10000, 25000, 50000, 100000, Infinity];
const LABELS = ["under 2k", "2–5k", "5–10k", "10–25k", "25–50k", "50–100k", "over 100k"];
const sizes = EDGES.slice(0, -1).map((lo, i) => {
  const hi = EDGES[i + 1]!;
  return {
    label: LABELS[i]!,
    count: communes.filter((c) => {
      const t = c.population["2024"].total;
      return t !== null && t >= lo && t < hi;
    }).length,
  };
});

/* 3. Whether the crosswalk holds up. ----------------------------------------- */

/**
 * The 207 renumbered communes got their 2014 figure by a name-and-exhaustion match
 * rather than by a code that stayed put. If those matches were wrong, their implied
 * growth would scatter differently from the 1,286 communes whose code never changed.
 * This is the comparison, so a reader can judge the reconciliation instead of trusting it.
 */
const quantiles = (values: number[]) => {
  const v = [...values].sort((a, b) => a - b);
  const at = (q: number) => v[Math.min(v.length - 1, Math.floor(v.length * q))]!;
  return { p10: at(0.1), p25: at(0.25), median: at(0.5), p75: at(0.75), p90: at(0.9) };
};

const BASES = [
  { basis: "exact_code", label: "Code unchanged since 2014" },
  { basis: "crosswalk", label: "Renumbered, matched by the crosswalk" },
];
const spread = BASES.map(({ basis, label }) => {
  const pct = communes
    .filter((c) => c.population.change?.basis === basis)
    .map((c) => c.population.change!.pct);
  return { basis, label, count: pct.length, ...quantiles(pct) };
});

/* 4. Urban communes are a small minority everywhere. ------------------------- */

const urban = regions
  .map((region) => {
    const inRegion = communes.filter((c) => c.parents.region === region.code);
    const u = inRegion.filter((c) => c.type === "urban").length;
    return { code: region.code, name: region.name.fr, urban: u, total: inRegion.length };
  })
  .sort((a, b) => b.urban / b.total - a.urban / a.total);

await mkdir("site/src/generated", { recursive: true });
await writeFile(
  "site/src/generated/charts.ts",
  `// Generated by site/scripts/charts.ts from data/v1/attributes. Do not edit.
export const change = ${JSON.stringify(change, null, 2)};

export const sizes = ${JSON.stringify(sizes, null, 2)};

export const spread = ${JSON.stringify(spread, null, 2)};

export const urban = ${JSON.stringify(urban, null, 2)};
`,
);

console.log(
  `charts: ${change.length} régions, ${sizes.length} size buckets, ` +
    `${spread.map((s) => `${s.basis}=${s.count}`).join(" ")}`,
);
