/**
 * The download list, built from the files that actually exist under data/v1 with their
 * real sizes. A file named here that is missing fails the build, which is how a link to
 * data/v1/crosswalk/crosswalk.json — a path that never existed — stays gone.
 */
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";

interface Group {
  key: string;
  licence: "hcp" | "odbl";
  files: { label: string; path: string }[];
}

const regions = JSON.parse(await readFile("data/v1/attributes/regions.json", "utf8")) as {
  code: string;
  name: { fr: string };
}[];

// Ordered so the narrow groups pair up on the two-column grid and the full-width
// boundaries row does not leave a hole beside the one before it.
const GROUPS: Group[] = [
  {
    key: "dlCommunes",
    licence: "hcp",
    files: [
      { label: "JSON", path: "data/v1/attributes/communes.json" },
      { label: "CSV", path: "data/v1/attributes/communes.csv" },
    ],
  },
  { key: "dlRegions", licence: "hcp", files: [{ label: "JSON", path: "data/v1/attributes/regions.json" }] },
  { key: "dlProvinces", licence: "hcp", files: [{ label: "JSON", path: "data/v1/attributes/provinces.json" }] },
  { key: "dlCercles", licence: "hcp", files: [{ label: "JSON", path: "data/v1/attributes/cercles.json" }] },
  {
    key: "dlArrondissements",
    licence: "hcp",
    files: [{ label: "JSON", path: "data/v1/attributes/arrondissements.json" }],
  },
  {
    key: "dlCrosswalk",
    licence: "hcp",
    files: [
      { label: "JSON", path: "data/v1/crosswalk/2014-2024.json" },
      { label: "CSV", path: "data/v1/crosswalk/2014-2024.csv" },
    ],
  },
  {
    key: "dlBoundaries",
    licence: "odbl",
    // One file per région, labelled by the région it holds rather than by its code.
    files: regions.map((r) => ({ label: r.name.fr, path: `data/v1/geometry/${r.code}.topojson` })),
  },
  { key: "dlSources", licence: "hcp", files: [{ label: "JSON", path: "data/v1/sources.json" }] },
];

const missing: string[] = [];
const groups = [];
for (const group of GROUPS) {
  const files = [];
  for (const file of group.files) {
    try {
      const { size } = await stat(file.path);
      files.push({ label: file.label, href: `/${file.path}`, bytes: size });
    } catch {
      missing.push(file.path);
    }
  }
  groups.push({ key: group.key, licence: group.licence, files });
}
if (missing.length > 0) {
  throw new Error(`the download list names files that do not exist:\n  ${missing.join("\n  ")}`);
}

await mkdir("site/src/generated", { recursive: true });
await writeFile(
  "site/src/generated/downloads.ts",
  `// Generated by site/scripts/downloads.ts from data/v1. Do not edit.
export const downloads = ${JSON.stringify(groups, null, 2)} as const;
`,
);
console.log(`downloads: ${groups.reduce((n, g) => n + g.files.length, 0)} files in ${groups.length} groups`);
