/**
 * The hierarchy strip on the home page, taken from the dataset so every figure on it is
 * the published one. Two chains, because the tiers are not a single ladder: a rural
 * commune sits under a cercle, and an urban one does not: it may instead hold
 * arrondissements. Showing both is the only honest way to draw five levels.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";

const ATTR = "data/v1/attributes";

interface Row {
  code: string;
  type?: string;
  name: { fr: string; ar: string };
  population?: { "2024"?: { total: number | null } };
  parents?: { province: string; cercle: string | null };
  provinceCode?: string;
  communeCode?: string;
}

const read = async (name: string) =>
  JSON.parse(await readFile(`${ATTR}/${name}.json`, "utf8")) as Row[];

const [regions, provinces, cercles, communes, arrondissements] = await Promise.all(
  ["regions", "provinces", "cercles", "communes", "arrondissements"].map(read),
);

const pick = <T extends Row>(rows: T[], code: string) => {
  const row = rows.find((r) => r.code === code);
  if (!row) throw new Error(`the hierarchy strip wants ${code}, which the dataset does not have`);
  return row;
};

const REGION = "01";
const PROVINCE = "01.511";
const CERCLE = "01.511.05";
const URBAN = "01.511.01.0";

const rural = communes.find((c) => c.parents?.cercle === CERCLE);
if (!rural) throw new Error(`no commune sits under cercle ${CERCLE}`);
const arrondissement = arrondissements.find((a) => a.communeCode === URBAN);
if (!arrondissement) throw new Error(`no arrondissement sits under commune ${URBAN}`);

const entry = (row: Row, level: string) => ({
  code: row.code,
  level,
  fr: row.name.fr,
  ar: row.name.ar,
  population: row.population?.["2024"]?.total ?? null,
});

const chain = [
  entry(pick(regions, REGION), "region"),
  // Tanger-Assilah is a préfecture, not a province. The tier holds 62 provinces, 13
  // préfectures and 8 préfectures d'arrondissements, so labelling every row with one
  // generic name would make the ladder say something untrue about this one.
  entry(pick(provinces, PROVINCE), pick(provinces, PROVINCE).type ?? "province"),
  entry(pick(cercles, CERCLE), "cercle"),
  entry(rural, "commune"),
  entry(pick(communes, URBAN), "commune"),
  entry(arrondissement, "arrondissement"),
];

await mkdir("site/src/generated", { recursive: true });
await writeFile(
  "site/src/generated/hierarchy.ts",
  `// Generated by site/scripts/hierarchy.ts from data/v1/attributes. Do not edit.
export interface Entry {
  code: string;
  level: string;
  fr: string;
  ar: string;
  population: number | null;
}

export const chain: Entry[] = ${JSON.stringify(chain, null, 2)};

export const counts = {
  regions: ${regions.length},
  provinces: ${provinces.length},
  cercles: ${cercles.length},
  communes: ${communes.length},
  arrondissements: ${arrondissements.length},
};
`,
);
console.log(`hierarchy: ${chain.length} rows, counts from ${communes.length} communes`);
